# Generated by Django 4.2 on 2023-05-16 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('directores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_directores', to='mi_app.directores')),
            ],
        ),
        migrations.CreateModel(
            name='Estadios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('posicion', models.CharField(max_length=200)),
                ('num_player', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Poblaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ligas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='')),
                ('equipos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligas_equipos', to='mi_app.equipos')),
                ('poblacion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligas_poblaciones', to='mi_app.poblaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('state', models.CharField(max_length=200)),
                ('arbitro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_app.arbitros')),
                ('equipo1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juegos_equipo1', to='mi_app.equipos')),
                ('equipo2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juegos_equipo2', to='mi_app.equipos')),
                ('estadio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_app.estadios')),
                ('liga_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_app.ligas')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('minuto', models.CharField(max_length=200)),
                ('tarjeta', models.CharField(max_length=200)),
                ('player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_app.jugadores')),
            ],
        ),
        migrations.AddField(
            model_name='estadios',
            name='liga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.ligas'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='jugadores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_jugadores', to='mi_app.jugadores'),
        ),
        migrations.AddField(
            model_name='arbitros',
            name='liga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.ligas'),
        ),
    ]
