# Generated by Django 4.2 on 2023-05-16 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitros',
            name='liga_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitro_liga', to='mi_app.ligas'),
        ),
        migrations.AlterField(
            model_name='estadios',
            name='liga_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liga_estadio', to='mi_app.ligas'),
        ),
    ]
