# Generated by Django 4.2 on 2023-05-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='titulo',
            field=models.CharField(default='fadfd', max_length=200),
            preserve_default=False,
        ),
    ]
