# Generated by Django 4.2 on 2023-05-17 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_equipos_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='jugadores',
        ),
        migrations.AddField(
            model_name='jugadores',
            name='equipo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores_equipos', to='mi_app.equipos'),
        ),
    ]
