# Generated by Django 4.2 on 2023-05-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0006_remove_equipos_jugadores_jugadores_equipo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligas',
            name='poblacion_id',
        ),
        migrations.DeleteModel(
            name='Poblaciones',
        ),
    ]
