# Generated by Django 4.2 on 2023-05-17 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_remove_ligas_poblacion_id_delete_poblaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligas',
            name='equipos',
        ),
        migrations.AddField(
            model_name='equipos',
            name='ligas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_ligas', to='mi_app.ligas'),
        ),
    ]
