# Generated by Django 4.2 on 2023-05-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0008_remove_ligas_equipos_equipos_ligas'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadios',
            name='foto',
            field=models.ImageField(default='prueba', upload_to='estadios/'),
            preserve_default=False,
        ),
    ]
