# Generated by Django 4.2 on 2023-05-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0009_estadios_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
