# Generated by Django 4.2 on 2023-05-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0011_alter_juegos_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='state',
            field=models.CharField(choices=[('programado', 'Programado'), ('terminado', 'Terminado')], default='programado', max_length=20),
        ),
    ]
