# Generated by Django 4.2 on 2023-05-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0012_alter_juegos_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='posicion',
            field=models.CharField(choices=[('del', 'Delantero'), ('def', 'Defensa'), ('med', 'Medio Campista'), ('ban_der', 'Banda Derecha'), ('ban_izq', 'Banda Izquierda'), ('por', 'Portero')], max_length=200),
        ),
    ]
